In [23]:
import numpy as np
import pandas as pd

In [24]:
dis01 = { "name":['jay','sam','prashant','akhi','raj'],
         "mark" : [74,87,86,76,90],
         "city" : ['pune','sangli','satara','kolhapur','solapur']

}

In [25]:
df = pd.DataFrame(dis01)

In [27]:
df

       name  mark      city
0       jay    74      pune
1       sam    87    sangli
2  prashant    86    satara
3      akhi    76  kolhapur
4       raj    90   solapur

In [28]:
df.to_csv("friMarks.csv")

In [29]:
df.to_csv('firMarks.csv',index=False)

In [30]:
   df.tail(2)

   name  mark      city
3  akhi    76  kolhapur
4   raj    90   solapur

In [31]:
df.head()

       name  mark      city
0       jay    74      pune
1       sam    87    sangli
2  prashant    86    satara
3      akhi    76  kolhapur
4       raj    90   solapur

In [32]:
df.describe()

            mark
count   5.000000
mean   82.600000
std     7.127412
min    74.000000
25%    76.000000
50%    86.000000
75%    87.000000
max    90.000000

In [33]:
services = pd.read_csv ("services.csv")

In [34]:
services

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [38]:
services["wait_time"][0] = 12

C:\Users\jaij1\AppData\Local\Temp\ipykernel_2456\923201259.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  services["wait_time"][0] = 12

In [39]:
services

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,12,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,NaN,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [40]:
#services.to_csv(services.csv) 
# new file in csv use {to_}

In [46]:
pf = pd.DataFrame(services)

NameError: name 'dis1' is not defined

In [63]:
import pandas as pd
df2 = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [64]:
df2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [66]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [68]:
type(df2.head)

method

In [69]:
type(df2)

pandas.core.frame.DataFrame

In [73]:
df2.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [74]:
type(df2.tail)

method